version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /csds-client
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /envoy-curses
    schedule:
      interval: weekly
